@echo off

SET MumbleVersion=1.0.9

SET TOOLCHAIN=d:\toolchain

SET VSVER=10.0
SET LIB=
SET QT_DIR=C:\Qt\Qt5.2.1\5.2.1\msvc2010
SET JOM_DIR=%TOOLCHAIN%\jom
SET VLD_DIR=%TOOLCHAIN%\vld
SET MYSQL_DIR=%TOOLCHAIN%\mysql
SET NASM_DIR=%TOOLCHAIN%\nasm
SET ICE_DIR=%TOOLCHAIN%\ice
SET PROTOBUF_DIR=%TOOLCHAIN%\protobuf
SET LIBSNDFILE_DIR=%TOOLCHAIN%\libsndfile
SET OPENSSL_DIR=%TOOLCHAIN%\openssl
SET BOOST_DIR=%TOOLCHAIN%\boost
SET GITBIN_DIR=%TOOLCHAIN%\bin
SET PERLBIN_DIR=%TOOLCHAIN%\perl\bin
SET ZLIB_DIR=%TOOLCHAIN%\zlib
SET DEBUGTOOLS_DIR=%TOOLCHAIN%\WDK\bin
SET CODESIGN_CERT=d:\jenkins\secure\code.p12

SET QMAKESPEC=%QT_DIR%\mkspecs\win32-msvc2010

SET DXSDK_DIR=%TOOLCHAIN%\dxsdk\
SET WindowsSDKDir=%TOOLCHAIN%\win8sdk
CALL "%WindowsSDKDir%\bin\SetEnv.cmd"
SET PATH=%TOOLCHAIN%\win8sdk\bin\x86;C:\Windows\Microsoft.NET\Framework\v4.0.30319;%GITBIN_DIR%;%PERLBIN_DIR%;%QT_DIR%\bin;%JOM_DIR%;%OPENSSL_DIR%\bin;%LIBSNDFILE_DIR%\bin;%MYSQL_DIR%\lib;%ICE_DIR%\bin\vc100;%PROTOBUF_DIR%\vsprojects\Release;%NASM_DIR%;%VLD_DIR%\bin;%PATH%

TITLE Mumble Development Environment
